### PR TITLE
migrate to php-parser v3.x

### PR DESCRIPTION
**Pull request by lvht**
migrate again

### CODE REVIEW

**Comment by lvht** [comment]
Hello guys @EvanDotPro @gianarb @sensorario @shawncplus @weynhamz 

The php 7.2 has been released. And the php-parser v1.x is too old to support the new php version.

We need to migrate the php-parser to the latest version.

**Comment by lvht** [comment]
By the way, I am a PHP developer and a heavy Vim/NeoVim user. I am maintaining the [phpcd.vim](https://github.com/lvht/phpcd.vim) and [phpfold.vim](https://github.com/lvht/phpfold.vim), both of which make Vim/NeoVim better for PHP developing.

And I would like to apply to join your php-vim group, and make Vim/NeoVim better for PHP developer.

**Comment by lvht** [comment]
Is there any body?

**Comment by mgallego** [comment]
Please review and accept the PR if is possible

**Comment by gianarb** [comment]
Thanks guys

**Comment by lvht** [comment]
@gianarb would you like to make me join your group?

**Pull request merged**
