### PR TITLE
Rebased performance parts of #23, passes unit tests

### PR DESCRIPTION
**Pull request by mr-russ**

### CODE REVIEW

**Comment by mr-russ** [comment]
Also with regard to the request to add testing coverage, I'm not in a position to do that.  It would require some time to invest.  I've now moved to using other tools am aren't using ctags anymore.

If you wish tests to be added, somebody will have to pick that up.

**Comment by gianarb** [comment]
No problem @mr-russ :) Thanks for this update I wait a check by @tomphp :)

@mr-russ if you don't use ctags what is your flow? :P Can you share with community your trick? :) For  example with a little PR here https://github.com/vim-php/vim-php.github.com/tree/master/_posts :) Thanks!

**Comment by tomphp** [comment]
At first glance this looks fine but tests would indeed but useful. I'll try and find some time it create some soon.

@mr-russ thanks this :-)

**Comment by gianarb** [comment]
Thanks @tomphp I wait your PR..
After merge release! :) :+1:

**Comment by gianarb** [comment]
I merged! :) Improvement in another pull request! :+1:

**Pull request merged**
