### PR TITLE
Fix failure in php5.3 and upgrade travis conf

### PR DESCRIPTION
**Pull request by gianarb**
This commit resolve the problem with php 5.3 compatibility and upgrade TravisCi's configuration

### CODE REVIEW

**Comment by gianarb** [comment]
@tomphp php 5.3 = Lot of problem :P

**Comment by tomphp** [comment]
Looks good to me. Do you want me to merge it?

**Comment by gianarb** [comment]
There are a lot of problem in Php 5.3 :)
https://travis-ci.org/vim-php/phpctags/jobs/55609733

**Comment by tomphp** [comment]
Sorry, I didn't see that on my mobile. Will fix it today ;-)

**Comment by gianarb** [comment]
Maybe I can try to fix it this evening but if you have a minut thanks!! :D

**Comment by tomphp** [comment]
Hmmm, not sure why PHP7 is failing?

**Comment by gianarb** [comment]
I don't kwno.. same question for HHVM

**Comment by gianarb** [comment]
I don't know.. Same question for hhvm

2015-03-24 16:17 GMT+01:00 Tom Oram <notifications@github.com>:

> Hmmm, not sure why PHP7 is failing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vim-php/phpctags/pull/44#issuecomment-85547281>.
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by tomphp** [comment]
It's possible that PHPUnit is not yet compatible? I could set up HHVM locally and try and investigate but I can't really to PHP7 atm.

**Comment by gianarb** [comment]
Php7 in this moment is into the build for monitoring its failure is not
checked into the build status :D

2015-03-24 16:49 GMT+01:00 Tom Oram <notifications@github.com>:

> It's possible that PHPUnit is not yet compatible? I could set up HHVM
> locally and try and investigate but I can't really to PHP7 atm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vim-php/phpctags/pull/44#issuecomment-85569663>.
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Pull request merged**
