### PR TITLE
Update to the last version of PHP-Parser (4.0)

### PR DESCRIPTION
**Pull request by No-OBu**
I have made this little update.
I have run phpunit, all seems to be working.
Tell me whether I can do anything else for help :)

### CODE REVIEW

**Comment by InFog** [comment]
:+1: Please merge this.

**Comment by Slamdunk** [comment]
Any news @gianarb ?

**Comment by Mte90** [comment]
ping!

**Comment by InFog** [comment]
Yay!

**Comment by Mte90** [comment]
Just waiting for the new release :-)

**Comment by gianarb** [comment]
https://github.com/vim-php/phpctags/releases/tag/0.7.0

**Comment by Mte90** [comment]
The readme need to be update for the phar version :-/

**Comment by moffe42** [comment]
Please note that this breaks the PHP 5.3 compat set in composer.json

**Pull request merged**
